INSERT INTO badges(name, description) VALUES ('Newbie', 'New User. No correct answers');
INSERT INTO badges(name, description) VALUES ('Starter', 'Made one question');
INSERT INTO badges(name, description) VALUES ('Helper', 'Answered a topic');
INSERT INTO badges(name, description) VALUES ('Loyal', 'Have one question marked as accepted');
INSERT INTO badges(name, description) VALUES ('Master', '10 correct answers');

insert into categories (name) values ('Sports');
insert into categories (name) values ('Industrial');
insert into categories (name) values ('Jewelery');
insert into categories (name) values ('Baby');
insert into categories (name) values ('Grocery');
insert into categories (name) values ('Movies');
insert into categories (name) values ('Movies');
insert into categories (name) values ('Baby');
insert into categories (name) values ('Outdoors');
insert into categories (name) values ('Electronics');
insert into categories (name) values ('Music');
insert into categories (name) values ('Kids');
insert into categories (name) values ('Home');
insert into categories (name) values ('Computers');
insert into categories (name) values ('Computers');
insert into categories (name) values ('Garden');
insert into categories (name) values ('Clothing');
insert into categories (name) values ('Jewelery');
insert into categories (name) values ('Clothing');
insert into categories (name) values ('Tools');
insert into categories (name) values ('Sports');
insert into categories (name) values ('Computers');
insert into categories (name) values ('Sports');
insert into categories (name) values ('Outdoors');
insert into categories (name) values ('Jewelery');
insert into categories (name) values ('Kids');
insert into categories (name) values ('Toys');
insert into categories (name) values ('Music');
insert into categories (name) values ('Kids');
insert into categories (name) values ('Music');
insert into categories (name) values ('Jewelery');
insert into categories (name) values ('Automotive');
insert into categories (name) values ('Tools');
insert into categories (name) values ('Music');
insert into categories (name) values ('Automotive');
insert into categories (name) values ('Baby');
insert into categories (name) values ('Electronics');
insert into categories (name) values ('Movies');
insert into categories (name) values ('Kids');
insert into categories (name) values ('Music');
insert into categories (name) values ('Clothing');
insert into categories (name) values ('Kids');
insert into categories (name) values ('Games');
insert into categories (name) values ('Books');
insert into categories (name) values ('Tools');
insert into categories (name) values ('Tools');
insert into categories (name) values ('Beauty');
insert into categories (name) values ('Movies');
insert into categories (name) values ('Toys');
insert into categories (name) values ('Tools');
insert into categories (name) values ('Electronics');
insert into categories (name) values ('Movies');
insert into categories (name) values ('Shoes');
insert into categories (name) values ('Toys');
insert into categories (name) values ('Music');
insert into categories (name) values ('Kids');
insert into categories (name) values ('Movies');
insert into categories (name) values ('Home');
insert into categories (name) values ('Music');
insert into categories (name) values ('Baby');
insert into categories (name) values ('Computers');
insert into categories (name) values ('Automotive');
insert into categories (name) values ('Books');
insert into categories (name) values ('Kids');
insert into categories (name) values ('Garden');
insert into categories (name) values ('Jewelery');
insert into categories (name) values ('Beauty');
insert into categories (name) values ('Games');
insert into categories (name) values ('Electronics');
insert into categories (name) values ('Home');
insert into categories (name) values ('Games');
insert into categories (name) values ('Shoes');
insert into categories (name) values ('Electronics');
insert into categories (name) values ('Computers');
insert into categories (name) values ('Health');
insert into categories (name) values ('Automotive');
insert into categories (name) values ('Outdoors');
insert into categories (name) values ('Baby');
insert into categories (name) values ('Beauty');
insert into categories (name) values ('Toys');
insert into categories (name) values ('Industrial');
insert into categories (name) values ('Kids');
insert into categories (name) values ('Automotive');
insert into categories (name) values ('Clothing');
insert into categories (name) values ('Books');
insert into categories (name) values ('Computers');
insert into categories (name) values ('Games');
insert into categories (name) values ('Automotive');
insert into categories (name) values ('Toys');
insert into categories (name) values ('Sports');
insert into categories (name) values ('Computers');
insert into categories (name) values ('Tools');
insert into categories (name) values ('Computers');
insert into categories (name) values ('Outdoors');
insert into categories (name) values ('Sports');
insert into categories (name) values ('Sports');
insert into categories (name) values ('Baby');
insert into categories (name) values ('Clothing');
insert into categories (name) values ('Books');
insert into categories (name) values ('Outdoors');

INSERT INTO userroles(name) VALUES ('Authenticated');
INSERT INTO userroles(name) VALUES ('Admin');
INSERT INTO userroles(name) VALUES ('Editor');

INSERT INTO locations(name) VALUES ('Porto');
INSERT INTO locations(name) VALUES ('Viseu');
INSERT INTO locations(name) VALUES ('Sao Paulo');
INSERT INTO locations(name) VALUES ('Paredes');
insert into locations (name) values ('Kamyanyuki');
insert into locations (name) values ('Metz');
insert into locations (name) values ('Santa Teresa');
insert into locations (name) values ('San Julian');
insert into locations (name) values ('Blobo');
insert into locations (name) values ('Huangzhai');
insert into locations (name) values ('Aveleda');
insert into locations (name) values ('Wuxiang');
insert into locations (name) values ('Yudai');
insert into locations (name) values ('Rosebank');
insert into locations (name) values ('Onzaga');
insert into locations (name) values ('Xiaolin');
insert into locations (name) values ('São Miguel do Rio Torto');
insert into locations (name) values ('Ash Shuhadā’');
insert into locations (name) values ('Breda');
insert into locations (name) values ('Kuma');
insert into locations (name) values ('Kasungu');
insert into locations (name) values ('Jingouhe');
insert into locations (name) values ('Lasek');
insert into locations (name) values ('Asquipata');
insert into locations (name) values ('Longfeng');
insert into locations (name) values ('Gaïtánion');
insert into locations (name) values ('Perístasi');
insert into locations (name) values ('Copa');
insert into locations (name) values ('Santuario');
insert into locations (name) values ('Orzesze');
insert into locations (name) values ('Malhão');
insert into locations (name) values ('Oemanu');
insert into locations (name) values ('Belén');
insert into locations (name) values ('Sumbersewu');
insert into locations (name) values ('Jiawu');
insert into locations (name) values ('Souto de Cima');
insert into locations (name) values ('Ternopil’');
insert into locations (name) values ('Shiziqiao');
insert into locations (name) values ('Aguelmous');
insert into locations (name) values ('Liqiao');
insert into locations (name) values ('Sangongqiao');
insert into locations (name) values ('Castanheira do Campo');
insert into locations (name) values ('Contraalmirante Cordero');
insert into locations (name) values ('Buzen');
insert into locations (name) values ('Villach');
insert into locations (name) values ('Mulhouse');
insert into locations (name) values ('Jerez');
insert into locations (name) values ('Rājshāhi');
insert into locations (name) values ('Thị Trấn Hà Trung');
insert into locations (name) values ('Layu');
insert into locations (name) values ('Chayuan');
insert into locations (name) values ('Laojunmiao');
insert into locations (name) values ('Huancapi');
insert into locations (name) values ('Potoni');
insert into locations (name) values ('Lewo');
insert into locations (name) values ('Ystad');
insert into locations (name) values ('Encontrados');
insert into locations (name) values ('Calilegua');
insert into locations (name) values ('Banjar Budakeling');
insert into locations (name) values ('Chernyakhovsk');
insert into locations (name) values ('Žitenice');
insert into locations (name) values ('Palestina de los Altos');
insert into locations (name) values ('Dawan');
insert into locations (name) values ('Washington');
insert into locations (name) values ('Lebak Timur');
insert into locations (name) values ('Salon-de-Provence');
insert into locations (name) values ('Ribamar');
insert into locations (name) values ('Jardim');
insert into locations (name) values ('Vysokovsk');
insert into locations (name) values ('Humble');
insert into locations (name) values ('San Juan de Manapiare');
insert into locations (name) values ('Ketapang');
insert into locations (name) values ('Timrå');
insert into locations (name) values ('Oke Iho');
insert into locations (name) values ('Dan Khun Thot');
insert into locations (name) values ('Gelin');
insert into locations (name) values ('Tianyi');
insert into locations (name) values ('Yong’an');
insert into locations (name) values ('Jacareí');
insert into locations (name) values ('Saint-Denis');
insert into locations (name) values ('Grybów');
insert into locations (name) values ('Duqu');
insert into locations (name) values ('Cova Figueira');
insert into locations (name) values ('Shanghudi');
insert into locations (name) values ('Zaandam');
insert into locations (name) values ('Lincheng');
insert into locations (name) values ('Lamadong');
insert into locations (name) values ('Jishi');
insert into locations (name) values ('Xiaolan');
insert into locations (name) values ('Rangpur');
insert into locations (name) values ('Penanggal');
insert into locations (name) values ('Cagmanaba');
insert into locations (name) values ('Madīnat Sittah Uktūbar');
insert into locations (name) values ('Azinhal');
insert into locations (name) values ('Bangekdewa');
insert into locations (name) values ('Pasuruan');
insert into locations (name) values ('Baziqiao');
insert into locations (name) values ('Sebu');
insert into locations (name) values ('Thetford-Mines');
insert into locations (name) values ('Mazowe');
insert into locations (name) values ('Kalanguy');
insert into locations (name) values ('Ivanava');
insert into locations (name) values ('Xiangyang');
insert into locations (name) values ('Masalovka');

INSERT INTO users (username, email, password, locationid, roleid)
VALUES ('editor', 'editor@editor.pt', '12345678', 1, 3);
INSERT INTO users (username, email, password, locationid, roleid)
VALUES ('warneduser', 'warneduser@user.pt', '12345678', 4, 1);
INSERT INTO users (username, email, password, locationid, roleid)
VALUES ('luistelmocosta', 'luistelmocosta@gmail.com', '12345678', 4, 2);
INSERT INTO users (username, email, password, locationid, roleid)
VALUES ('admin', 'admin@admin.pt', '12345678', 4, 2);
INSERT INTO users (username, email, password, locationid, roleid)
VALUES ('member', 'member@member.pt', '12345678', 3, 1);
INSERT INTO users (username, email, password, locationid, roleid)
VALUES ('ronaldo7', 'ronaldo@ronaldo.pt', '12345678', 3, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('cfuller0', 'cwatkins0@disqus.com', 'eCXLJXL', 73, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('pyoung1', 'awilliams1@sphinn.com', 'g58TSo5', 55, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('dcarter2', 'sgriffin2@apache.org', 'X0oACZPB', 43, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('mhenry3', 'sdunn3@forbes.com', 'NGvubdo', 32, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('wgraham4', 'hsullivan4@dailymail.co.uk', 'qffCv9', 85, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('cgeorge5', 'sarmstrong5@yale.edu', 'KMp8oGS', 15, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('clynch6', 'rdixon6@yahoo.com', 'MR2EmwzWHm2y', 27, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('malexander7', 'pkelley7@patch.com', 'mlTSYuE9udF', 30, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('estevens8', 'dyoung8@bing.com', 'cjKKfUhCq4', 40, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('kjackson9', 'pmcdonald9@marketwatch.com', 'M7pacvs51', 7, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jandrewsa', 'pkima@multiply.com', '4C5GlIQ', 55, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('mwilliamsb', 'rreidb@sfgate.com', 'bu1LzN3bjin1', 16, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('ckelleyc', 'flittlec@technorati.com', 'AokjOQmcrkM', 52, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('mdixond', 'rbryantd@howstuffworks.com', '4647h49kNuID', 40, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('vnguyene', 'bgilberte@xing.com', 'vdTZ3R28J', 17, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('crayf', 'mthomasf@stumbleupon.com', '8BMhXNVzwy', 22, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('amedinag', 'aalexanderg@disqus.com', 'wHc7Q8O', 55, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('bmurphyh', 'croseh@comcast.net', 'cyCti87i', 90, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('tjacobsi', 'rhansoni@psu.edu', '988ieJXBJ0uC', 42, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('carmstrongj', 'jlittlej@shop-pro.jp', 'V3nxid', 28, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('dpiercek', 'mmorenok@hc360.com', 'eActzzFZ', 27, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('slittlel', 'efoxl@usatoday.com', '727tKDTXU6', 25, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('cgardnerm', 'sortizm@163.com', 'I4DJvx65', 56, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('dmeyern', 'dwashingtonn@e-recht24.de', 'sStOKsUA', 81, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('dandrewso', 'jscotto@ifeng.com', 'o6WFahkf', 20, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('amarshallp', 'brichardsonp@altervista.org', 'BBWjvHZ', 11, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('hmccoyq', 'landersonq@dyndns.org', 'nC6quZt3Vu', 22, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('aroser', 'rburtonr@pen.io', '8wX7HX2FWd', 62, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('mriveras', 'mnicholss@newyorker.com', 'kfkNCFzL', 58, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('sburket', 'dhartt@unc.edu', 'zbuB1z', 34, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('krobertsu', 'egarciau@businessweek.com', 'YwG7NNpSHXP0', 15, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('sdunnv', 'pkennedyv@blinklist.com', 'ghH1UBOwSII', 80, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('aruizw', 'pweaverw@myspace.com', 'UFW8qUxR0zvV', 38, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('rnguyenx', 'kwalkerx@bigcartel.com', '7ZKZ4Se9kZ', 74, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jcoopery', 'wbakery@tinyurl.com', 'yeAAjrJe', 38, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('dedwardsz', 'aclarkz@buzzfeed.com', 'HoUni2ObeA', 61, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('sfrazier10', 'lboyd10@webeden.co.uk', 'eWKI454L4E', 19, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jhanson11', 'ecarroll11@slate.com', 'QiqQulDAKY', 35, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('amatthews12', 'fhanson12@google.de', 'nuiS8pp', 40, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('proberts13', 'jpayne13@de.vu', '3HgIN4av', 15, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('ajames14', 'skelley14@printfriendly.com', 'ERpBVk4l', 71, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('llarson15', 'jpowell15@microsoft.com', '8xSFxIiXkOU', 42, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('nfowler16', 'carmstrong16@youku.com', 'j1TkDtT5GChP', 65, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('wwright17', 'rrogers17@prlog.org', 'z7phI4jH', 35, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jmcdonald18', 'along18@cbslocal.com', 'L7Hjmlm42', 31, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('esnyder19', 'akelley19@unicef.org', '4KSqD9SB', 16, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('dyoung1a', 'bevans1a@cocolog-nifty.com', '1b3HaMb', 17, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('cwallace1b', 'jperkins1b@imgur.com', '8GaS8Ywe', 79, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('mfoster1c', 'raustin1c@virginia.edu', 'bikq2ItVaiO', 39, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('cparker1d', 'jedwards1d@simplemachines.org', 'jSmyorq3DA3', 61, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jsmith1e', 'mbowman1e@homestead.com', 'SvWTCT2', 89, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('dclark1f', 'fphillips1f@mac.com', 'CrjZ6hg', 11, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('nfrazier1g', 'kallen1g@fotki.com', 'G8Qc6zdtb', 50, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('gbrown1h', 'bwalker1h@cnbc.com', 'NhqOqF', 52, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('sharrison1i', 'etaylor1i@nyu.edu', 'yJei58AOb', 81, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jaustin1j', 'mlewis1j@rambler.ru', 'ZdmbRUY', 70, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jrogers1k', 'clong1k@yellowbook.com', 'BdpM6hwDdKX', 40, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jmartin1l', 'bwatson1l@smugmug.com', 'kluqiB9C', 30, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jhall1m', 'pcastillo1m@godaddy.com', 'hj0ZJsygJ', 87, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('plee1n', 'mgibson1n@cornell.edu', '5GmYA7SKA', 3, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('dporter1o', 'bfields1o@senate.gov', 'iZFTO4u2KCgk', 28, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jkim1p', 'tdiaz1p@artisteer.com', 'SEO7kfj9', 83, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('ehernandez1q', 'dross1q@1und1.de', 'K1N4MGc3YqP', 53, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('gmiller1r', 'prichardson1r@surveymonkey.com', 'ju00Q2masJKf', 4, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('ewallace1s', 'eprice1s@prlog.org', 'KThqVf', 91, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('lkelley1t', 'ecole1t@goo.gl', 'QCivhCXGwM0', 83, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('cshaw1u', 'gwatkins1u@csmonitor.com', 'ZvvQYcDwZ4vx', 41, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('egreene1v', 'thunt1v@prlog.org', 'YvxJocvAWfe', 47, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jtaylor1w', 'dlawson1w@marriott.com', 'KMKp2K3JgO', 70, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('bthomas1x', 'jfisher1x@google.co.jp', 'yamh22QaNhQ', 46, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('lallen1y', 'ccrawford1y@sciencedirect.com', '0khnJh', 91, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('awarren1z', 'aanderson1z@arstechnica.com', 'TQnrVaN', 84, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('rwells20', 'agreen20@zdnet.com', '2pjRjX', 25, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('blane21', 'pfuller21@who.int', 'pBgMvolRYV', 9, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('hturner22', 'ageorge22@slate.com', 'YGAwbziY2Bg', 10, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('fcox23', 'vmorales23@prweb.com', 'z9SgT0Q', 43, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('tclark24', 'rromero24@w3.org', 'Ur3ezNVZa', 1, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('rcox25', 'rsullivan25@howstuffworks.com', '4NY8kbSO', 66, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('scarpenter26', 'jgilbert26@wordpress.org', 'Ri4qBabTeLB', 59, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('fwallace27', 'dray27@squidoo.com', 'MClUXQL51e', 61, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('knichols28', 'tphillips28@wp.com', 'Lvpp7AdPYJ', 83, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('sroberts29', 'slane29@chron.com', '1L0VP0', 92, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('mfisher2a', 'etaylor2a@bizjournals.com', 'MGde02', 86, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('rpierce2b', 'ktaylor2b@aol.com', 'nzQVDKVsxpxi', 34, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jdunn2c', 'pfreeman2c@spotify.com', 'mFGwvXHsNPg', 66, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('rduncan2d', 'dgriffin2d@shop-pro.jp', 'Oe1a8TM1E4t', 30, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('lgeorge2e', 'jroberts2e@tiny.cc', '3jbC6qFuf', 40, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('ljones2f', 'bstanley2f@indiegogo.com', 'XGMgcn7gZ9j', 13, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('mlynch2g', 'wpalmer2g@globo.com', 'UKS1gx', 84, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('sjohnson2h', 'revans2h@discuz.net', 'rmy4ZkCO9b', 92, 1);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('gmorris2i', 'sjackson2i@sfgate.com', 'iItAGleErkye', 9, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('rhoward2j', 'dcarr2j@utexas.edu', 'mISgaJ5R', 15, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('ralvarez2k', 'tjordan2k@bluehost.com', 'R6iqI5pEeZ', 26, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('crobinson2l', 'ngonzales2l@bigcartel.com', 'yMPDBniqW1', 81, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('rstone2m', 'sgriffin2m@vinaora.com', 'LNB4sGg', 36, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('kgreen2n', 'rcooper2n@reddit.com', 'UVeFJ95', 71, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('abutler2o', 'cgrant2o@howstuffworks.com', 'elKmKGK', 2, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('mharrison2p', 'khenry2p@studiopress.com', '15d7kYZSxq56', 65, 2);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('jwatson2q', 'dharrison2q@craigslist.org', 'QEOV6XOVqu', 61, 3);
INSERT INTO users (username, email, password, locationid, roleid) VALUES ('aholmes2r', 'wlewis2r@mediafire.com', 'wLe1ZIe7s', 79, 3);
INSERT INTO modregisters(reason, userid_author, userid_target) VALUES ('Offensive Speech', 3, 4);
INSERT INTO modregisters(reason, userid_author, userid_target) VALUES ('Wrong question structure', 3, 4);
INSERT INTO modregisters(reason, userid_author, userid_target) VALUES ('Bad username', 3, 4);
INSERT INTO modregisters(reason, userid_author, userid_target) VALUES ('Third Warning', 4, 4);

INSERT INTO warnings(warningid) VALUES (2);
INSERT INTO warnings(warningid) VALUES (3);

INSERT INTO bans(banid, end_date) VALUES (2, '2018-03-29 01:05:00');
INSERT INTO bans(banid, end_date) VALUES (4, '2018-04-04 01:05:00');

INSERT INTO publications(body, userid) VALUES ('When is the next full moon?', 3);
INSERT INTO publications(body, userid) VALUES ('What is the cheapest way to go to London?',3);
INSERT INTO publications(body, userid) VALUES ('Do I get pregnant from sitting in public toilets?', 3);
INSERT INTO publications(body, userid) VALUES ('Whos the best football player in the world?', 3);
INSERT INTO publications(body, userid) VALUES ('The next full moon will be on 22nd June 2017', 4);
INSERT INTO publications(body, userid) VALUES ('You should explore Ryanair/EasyJet flight promotions', 4);
INSERT INTO publications(body, userid) VALUES ('Please tell me youre not serious, mate', 4);
INSERT INTO publications(body, userid) VALUES ('That question has no rational answer. Both players are great! Enjoy them while you can!', 4);
INSERT INTO publications(body, userid) VALUES ('Cristiano Ronaldo only thinks about himself', 5);
INSERT INTO publications(body, userid) VALUES ('Cristiano Ronaldo carries his National Team', 6);
insert into publications (body, userid) values ('libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla', 96);
insert into publications (body, userid) values ('nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam', 52);
insert into publications (body, userid) values ('habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque', 29);
insert into publications (body, userid) values ('nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc', 97);
insert into publications (body, userid) values ('blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 8);
insert into publications (body, userid) values ('ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 99);
insert into publications (body, userid) values ('vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', 92);
insert into publications (body, userid) values ('posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi', 61);
insert into publications (body, userid) values ('duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus', 95);
insert into publications (body, userid) values ('blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et', 24);
insert into publications (body, userid) values ('adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget', 45);
insert into publications (body, userid) values ('suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce', 48);
insert into publications (body, userid) values ('tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi', 65);
insert into publications (body, userid) values ('odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 67);
insert into publications (body, userid) values ('tempor convallis nulla neque libero convallis eget eleifend luctus ultricies', 86);
insert into publications (body, userid) values ('aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', 65);
insert into publications (body, userid) values ('scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean', 85);
insert into publications (body, userid) values ('rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia', 71);
insert into publications (body, userid) values ('egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero', 3);
insert into publications (body, userid) values ('adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam', 19);
insert into publications (body, userid) values ('magna ac consequat metus sapien ut nunc vestibulum ante ipsum', 72);
insert into publications (body, userid) values ('ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac', 18);
insert into publications (body, userid) values ('sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum', 26);
insert into publications (body, userid) values ('ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam', 56);
insert into publications (body, userid) values ('potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', 23);
insert into publications (body, userid) values ('lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum', 64);
insert into publications (body, userid) values ('primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus', 61);
insert into publications (body, userid) values ('ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque', 82);
insert into publications (body, userid) values ('quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus', 58);
insert into publications (body, userid) values ('arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu', 19);
insert into publications (body, userid) values ('nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', 91);
insert into publications (body, userid) values ('lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac', 100);
insert into publications (body, userid) values ('nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', 64);
insert into publications (body, userid) values ('platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo', 59);
insert into publications (body, userid) values ('orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a', 70);
insert into publications (body, userid) values ('amet justo morbi ut odio cras mi pede malesuada in imperdiet et', 39);
insert into publications (body, userid) values ('elementum nullam varius nulla facilisi cras non velit nec nisi vulputate', 82);
insert into publications (body, userid) values ('vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque', 10);
insert into publications (body, userid) values ('sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', 93);
insert into publications (body, userid) values ('urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec', 68);
insert into publications (body, userid) values ('porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque', 86);
insert into publications (body, userid) values ('felis donec semper sapien a libero nam dui proin leo odio', 69);
insert into publications (body, userid) values ('orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', 37);
insert into publications (body, userid) values ('ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices', 53);
insert into publications (body, userid) values ('luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat', 93);
insert into publications (body, userid) values ('sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam', 25);
insert into publications (body, userid) values ('faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 36);
insert into publications (body, userid) values ('vestibulum quam sapien varius ut blandit non interdum in ante vestibulum', 83);
insert into publications (body, userid) values ('in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis', 55);
insert into publications (body, userid) values ('amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique', 19);
insert into publications (body, userid) values ('mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', 88);
insert into publications (body, userid) values ('ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', 58);
insert into publications (body, userid) values ('nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa', 84);
insert into publications (body, userid) values ('in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id', 59);
insert into publications (body, userid) values ('vestibulum sit amet cursus id turpis integer aliquet massa id lobortis', 90);
insert into publications (body, userid) values ('curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', 60);
insert into publications (body, userid) values ('convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam', 17);
insert into publications (body, userid) values ('quis orci eget orci vehicula condimentum curabitur in libero ut', 30);
insert into publications (body, userid) values ('at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat', 81);
insert into publications (body, userid) values ('proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in', 97);
insert into publications (body, userid) values ('quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst', 31);
insert into publications (body, userid) values ('eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', 4);
insert into publications (body, userid) values ('gravida sem praesent id massa id nisl venenatis lacinia aenean', 64);
insert into publications (body, userid) values ('vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis', 80);
insert into publications (body, userid) values ('lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere', 67);
insert into publications (body, userid) values ('erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla', 89);
insert into publications (body, userid) values ('curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 87);
insert into publications (body, userid) values ('in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed', 24);
insert into publications (body, userid) values ('a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel', 78);
insert into publications (body, userid) values ('euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis', 19);
insert into publications (body, userid) values ('eu massa donec dapibus duis at velit eu est congue elementum in', 28);
insert into publications (body, userid) values ('nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', 2);
insert into publications (body, userid) values ('pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla', 41);
insert into publications (body, userid) values ('nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi', 88);
insert into publications (body, userid) values ('ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat', 97);
insert into publications (body, userid) values ('est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum', 30);
insert into publications (body, userid) values ('aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel', 16);
insert into publications (body, userid) values ('accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla', 50);
insert into publications (body, userid) values ('duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate', 9);
insert into publications (body, userid) values ('cursus vestibulum proin eu mi nulla ac enim in tempor turpis', 53);
insert into publications (body, userid) values ('et magnis dis parturient montes nascetur ridiculus mus etiam vel augue', 51);
insert into publications (body, userid) values ('eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat', 47);
insert into publications (body, userid) values ('quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede', 50);
insert into publications (body, userid) values ('aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer', 8);
insert into publications (body, userid) values ('et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse', 88);
insert into publications (body, userid) values ('magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus', 52);
insert into publications (body, userid) values ('pellentesque volutpat dui maecenas tristique est et tempus semper est', 77);
insert into publications (body, userid) values ('in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum', 20);
insert into publications (body, userid) values ('in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus', 3);
insert into publications (body, userid) values ('purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', 30);
insert into publications (body, userid) values ('vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 76);
insert into publications (body, userid) values ('sodales sed tincidunt eu felis fusce posuere felis sed lacus', 77);
insert into publications (body, userid) values ('rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio', 80);
insert into publications (body, userid) values ('quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh', 82);
insert into publications (body, userid) values ('natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque', 9);
insert into publications (body, userid) values ('interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at', 35);
insert into publications (body, userid) values ('nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam', 94);
insert into publications (body, userid) values ('in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet', 21);
insert into publications (body, userid) values ('ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque', 83);
insert into publications (body, userid) values ('augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 1);

INSERT INTO questions VALUES (1,'viverra erat dui sagittis aliquam',21);
INSERT INTO questions VALUES (2,'metus sapien mollis est',83);
INSERT INTO questions VALUES (3,'viverra quis sollicitudin erat sit',76);
INSERT INTO questions VALUES (4,'Curae varius',26);
INSERT INTO questions VALUES (5,'Suspendisse tempus',95);
INSERT INTO questions VALUES (6,'odio fringilla',79);
INSERT INTO questions VALUES (7,'convallis litora et',21);
INSERT INTO questions VALUES (8,'accumsan ut quam pede',86);
INSERT INTO questions VALUES (9,'hendrerit Morbi',66);
INSERT INTO questions VALUES (10,'sollicitudin nec risus',20);
INSERT INTO questions VALUES (11,'dui morbi',40);
INSERT INTO questions VALUES (12,'lacinia Lorem laoreet lectus feugiat',32);
INSERT INTO questions VALUES (13,'libero sapien id aliquam leo',18);
INSERT INTO questions VALUES (14,'Vestibulum Proin',21);
INSERT INTO questions VALUES (15,'facilisi sapien',51);
INSERT INTO questions VALUES (16,'Curae a ligula',96);
INSERT INTO questions VALUES (17,'pellentesque laoreet sociis',18);
INSERT INTO questions VALUES (18,'Maecenas pellentesque',83);
INSERT INTO questions VALUES (19,'nonummy inceptos cursus',53);
INSERT INTO questions VALUES (20,'feugiat orci nascetur penatibus',25);
INSERT INTO questions VALUES (21,'malesuada interdum Curabitur in massa',1);
INSERT INTO questions VALUES (22,'adipiscing laoreet',31);
INSERT INTO questions VALUES (23,'nostra libero libero nunc ac',2);
INSERT INTO questions VALUES (24,'eleifend facilisis Fusce suscipit',73);
INSERT INTO questions VALUES (25,'augue interdum',83);
INSERT INTO questions VALUES (26,'mus habitant aliquam',72);
INSERT INTO questions VALUES (27,'Etiam malesuada sociosqu fermentum euismod',20);
INSERT INTO questions VALUES (28,'ornare Mauris taciti felis primis',72);
INSERT INTO questions VALUES (29,'interdum Sed vitae erat',97);
INSERT INTO questions VALUES (30,'porta at netus pharetra',58);
INSERT INTO questions VALUES (31,'tempor cubilia',11);
INSERT INTO questions VALUES (32,'scelerisque Vivamus ridiculus nec',12);
INSERT INTO questions VALUES (33,'ridiculus in Vivamus',14);
INSERT INTO questions VALUES (34,'consectetuer lorem sit massa mus',64);
INSERT INTO questions VALUES (35,'mattis dolor in',96);
INSERT INTO questions VALUES (36,'Proin Phasellus natoque',39);
INSERT INTO questions VALUES (37,'convallis gravida et consectetuer',64);
INSERT INTO questions VALUES (38,'nec libero posuere',39);
INSERT INTO questions VALUES (39,'fames fames blandit',14);
INSERT INTO questions VALUES (40,'vitae metus libero vitae',74);

INSERT INTO answers VALUES (41,13);
INSERT INTO answers VALUES (42,30);
INSERT INTO answers VALUES (43,13);
INSERT INTO answers VALUES (44,3);
INSERT INTO answers VALUES (45,38);
INSERT INTO answers VALUES (46,35);
INSERT INTO answers VALUES (47,14);
INSERT INTO answers VALUES (48,4);
INSERT INTO answers VALUES (49,36);
INSERT INTO answers VALUES (50,14);
INSERT INTO answers VALUES (51,40);
INSERT INTO answers VALUES (52,17);
INSERT INTO answers VALUES (53,19);
INSERT INTO answers VALUES (54,19);
INSERT INTO answers VALUES (55,23);
INSERT INTO answers VALUES (56,34);
INSERT INTO answers VALUES (57,34);
INSERT INTO answers VALUES (58,5);
INSERT INTO answers VALUES (59,40);
INSERT INTO answers VALUES (60,31);
INSERT INTO answers VALUES (61,29);
INSERT INTO answers VALUES (62,20);
INSERT INTO answers VALUES (63,18);
INSERT INTO answers VALUES (64,21);
INSERT INTO answers VALUES (65,27);
INSERT INTO answers VALUES (66,33);
INSERT INTO answers VALUES (67,36);
INSERT INTO answers VALUES (68,39);
INSERT INTO answers VALUES (69,16);
INSERT INTO answers VALUES (70,23);
INSERT INTO answers VALUES (71,7);
INSERT INTO answers VALUES (72,36);
INSERT INTO answers VALUES (73,36);
INSERT INTO answers VALUES (74,38);
INSERT INTO answers VALUES (75,25);
INSERT INTO answers VALUES (76,8);
INSERT INTO answers VALUES (77,13);
INSERT INTO answers VALUES (78,11);
INSERT INTO answers VALUES (79,5);
INSERT INTO answers VALUES (80,26);



INSERT INTO comments VALUES (81);
INSERT INTO comments VALUES (82);
INSERT INTO comments VALUES (83);
INSERT INTO comments VALUES (84);
INSERT INTO comments VALUES (85);
INSERT INTO comments VALUES (86);
INSERT INTO comments VALUES (87);
INSERT INTO comments VALUES (88);
INSERT INTO comments VALUES (89);
INSERT INTO comments VALUES (90);
INSERT INTO comments VALUES (91);
INSERT INTO comments VALUES (92);
INSERT INTO comments VALUES (93);
INSERT INTO comments VALUES (94);
INSERT INTO comments VALUES (95);
INSERT INTO comments VALUES (96);
INSERT INTO comments VALUES (97);
INSERT INTO comments VALUES (98);
INSERT INTO comments VALUES (99);
INSERT INTO comments VALUES (100);
INSERT INTO comments VALUES (101);
INSERT INTO comments VALUES (102);
INSERT INTO comments VALUES (103);
INSERT INTO comments VALUES (104);
INSERT INTO comments VALUES (105);
INSERT INTO comments VALUES (106);
INSERT INTO comments VALUES (107);
INSERT INTO comments VALUES (108);
INSERT INTO comments VALUES (109);
INSERT INTO comments VALUES (110);

INSERT INTO questioncomments VALUES (81,34);
INSERT INTO questioncomments VALUES (82,7);
INSERT INTO questioncomments VALUES (83,4);
INSERT INTO questioncomments VALUES (84,11);
INSERT INTO questioncomments VALUES (85,5);
INSERT INTO questioncomments VALUES (86,7);
INSERT INTO questioncomments VALUES (87,16);
INSERT INTO questioncomments VALUES (88,24);
INSERT INTO questioncomments VALUES (89,7);
INSERT INTO questioncomments VALUES (90,6);
INSERT INTO questioncomments VALUES (91,12);
INSERT INTO questioncomments VALUES (92,25);
INSERT INTO questioncomments VALUES (93,33);
INSERT INTO questioncomments VALUES (94,12);
INSERT INTO questioncomments VALUES (95,9);

INSERT INTO answercomments VALUES (96,76);
INSERT INTO answercomments VALUES (97,62);
INSERT INTO answercomments VALUES (98,66);
INSERT INTO answercomments VALUES (99,68);
INSERT INTO answercomments VALUES (100,41);
INSERT INTO answercomments VALUES (101,49);
INSERT INTO answercomments VALUES (102,46);
INSERT INTO answercomments VALUES (103,62);
INSERT INTO answercomments VALUES (104,66);
INSERT INTO answercomments VALUES (105,44);
INSERT INTO answercomments VALUES (106,73);
INSERT INTO answercomments VALUES (107,54);
INSERT INTO answercomments VALUES (108,44);
INSERT INTO answercomments VALUES (109,74);
INSERT INTO answercomments VALUES (110,51);

INSERT INTO tags(name) VALUES ('real madrid');
INSERT INTO tags(name) VALUES ('moon');
INSERT INTO tags(name) VALUES ('flights');
INSERT INTO tags(name) VALUES ('pregnancy');
INSERT INTO tags(name) VALUES ('health');
INSERT INTO tags(name) VALUES ('football');
insert into tags (name) values ('matrices');
insert into tags (name) values ('Monitored');
insert into tags (name) values ('Cross-group');
insert into tags (name) values ('system-worthy');
insert into tags (name) values ('empowering');
insert into tags (name) values ('Intuitive');
insert into tags (name) values ('benchmark');
insert into tags (name) values ('Diverse');
insert into tags (name) values ('actuating');
insert into tags (name) values ('info-mediaries');
insert into tags (name) values ('systemic');
insert into tags (name) values ('Decentralized');
insert into tags (name) values ('Persevering');
insert into tags (name) values ('Graphic Interface');
insert into tags (name) values ('internet solution');
insert into tags (name) values ('Monitored');
insert into tags (name) values ('info-mediaries');
insert into tags (name) values ('content-based');
insert into tags (name) values ('global');
insert into tags (name) values ('systemic');
insert into tags (name) values ('Persistent');
insert into tags (name) values ('full-range');
insert into tags (name) values ('Sharable');
insert into tags (name) values ('Organic');
insert into tags (name) values ('interface');
insert into tags (name) values ('24 hour');
insert into tags (name) values ('discrete');
insert into tags (name) values ('Down-sized');
insert into tags (name) values ('Stand-alone');
insert into tags (name) values ('capacity');
insert into tags (name) values ('Customer-focused');
insert into tags (name) values ('5th generation');
insert into tags (name) values ('groupware');
insert into tags (name) values ('demand-driven');
insert into tags (name) values ('neutral');
insert into tags (name) values ('reciprocal');
insert into tags (name) values ('time-frame');
insert into tags (name) values ('instruction set');
insert into tags (name) values ('encoding');
insert into tags (name) values ('knowledge user');
insert into tags (name) values ('Quality-focused');
insert into tags (name) values ('Profit-focused');
insert into tags (name) values ('benchmark');
insert into tags (name) values ('Extended');
insert into tags (name) values ('Distributed');
insert into tags (name) values ('intermediate');
insert into tags (name) values ('heuristic');
insert into tags (name) values ('Advanced');
insert into tags (name) values ('Customer-focused');
insert into tags (name) values ('data-warehouse');
insert into tags (name) values ('Assimilated');
insert into tags (name) values ('migration');
insert into tags (name) values ('disintermediate');
insert into tags (name) values ('circuit');
insert into tags (name) values ('artificial intelligence');
insert into tags (name) values ('Progressive');
insert into tags (name) values ('eco-centric');
insert into tags (name) values ('capacity');
insert into tags (name) values ('incremental');
insert into tags (name) values ('composite');
insert into tags (name) values ('policy');
insert into tags (name) values ('archive');
insert into tags (name) values ('interactive');
insert into tags (name) values ('Open-source');
insert into tags (name) values ('middleware');
insert into tags (name) values ('Integrated');
insert into tags (name) values ('Automated');
insert into tags (name) values ('data-warehouse');
insert into tags (name) values ('Balanced');
insert into tags (name) values ('context-sensitive');
insert into tags (name) values ('conglomeration');
insert into tags (name) values ('scalable');
insert into tags (name) values ('contextually-based');
insert into tags (name) values ('knowledge base');
insert into tags (name) values ('initiative');
insert into tags (name) values ('multi-state');
insert into tags (name) values ('Fundamental');
insert into tags (name) values ('Automated');
insert into tags (name) values ('hybrid');
insert into tags (name) values ('zero defect');
insert into tags (name) values ('product');
insert into tags (name) values ('paradigm');
insert into tags (name) values ('leverage');
insert into tags (name) values ('zero defect');
insert into tags (name) values ('archive');
insert into tags (name) values ('maximized');
insert into tags (name) values ('contextually-based');
insert into tags (name) values ('stable');
insert into tags (name) values ('Balanced');
insert into tags (name) values ('support');
insert into tags (name) values ('local area network');
insert into tags (name) values ('leverage');
insert into tags (name) values ('responsive');
insert into tags (name) values ('project');
insert into tags (name) values ('toolset');
insert into tags (name) values ('object-oriented');
insert into tags (name) values ('ability');
insert into tags (name) values ('Balanced');
insert into tags (name) values ('conglomeration');
insert into tags (name) values ('Object-based');

INSERT INTO votes(VALUES, publicationid, userid) VALUES (1, 1, 1);
INSERT INTO votes(VALUES, publicationid, userid) VALUES (0, 1, 2);
INSERT INTO votes(VALUES, publicationid, userid) VALUES (-1, 2, 2);
INSERT INTO votes(VALUES, publicationid, userid) VALUES (1, 2, 3);
INSERT INTO votes(VALUES, publicationid, userid) VALUES (1, 3, 3);


INSERT INTO questiontags(questionid, tagid) VALUES (1, 2);
INSERT INTO questiontags(questionid, tagid) VALUES (2, 3);
INSERT INTO questiontags(questionid, tagid) VALUES (3, 4);
INSERT INTO questiontags(questionid, tagid) VALUES (3, 5);
INSERT INTO questiontags(questionid, tagid) VALUES (4, 1);
INSERT INTO questiontags(questionid, tagid) VALUES (4, 6);


INSERT INTO userbadges(userid, badgeid) VALUES (1, 1);
INSERT INTO userbadges(userid, badgeid) VALUES (1, 2);
INSERT INTO userbadges(userid, badgeid) VALUES (1, 3);
INSERT INTO userbadges(userid, badgeid) VALUES (1, 4);
INSERT INTO userbadges(userid, badgeid) VALUES (1, 5);
INSERT INTO userbadges(userid, badgeid) VALUES (2, 1);
INSERT INTO userbadges(userid, badgeid) VALUES (3, 1);
INSERT INTO userbadges(userid, badgeid) VALUES (3, 2);
INSERT INTO userbadges(userid, badgeid) VALUES (4, 1);
INSERT INTO userbadges(userid, badgeid) VALUES (4, 2);
INSERT INTO userbadges(userid, badgeid) VALUES (4, 3);
INSERT INTO userbadges(userid, badgeid) VALUES (4, 5);







