DROP TRIGGER IF EXISTS check_question ON public.questions;
DROP TRIGGER IF EXISTS check_answer ON public.answers;
DROP TRIGGER IF EXISTS check_comment ON public.comments;
DROP TRIGGER IF EXISTS questions_tsvector_update_trigger ON public.comments;
DROP TRIGGER IF EXISTS auto_ban_on_warning_limit ON public.warnings;
DROP TRIGGER IF EXISTS answer_update_question_timestamp ON public.publications;
DROP TABLE IF EXISTS warnings CASCADE;
DROP TABLE IF EXISTS badges CASCADE;
DROP TABLE IF EXISTS bans CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS userbadges CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS publications CASCADE;
DROP TABLE IF EXISTS modregisters CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS "tags" CASCADE;
DROP TABLE IF EXISTS "userroles" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "votes" CASCADE;
DROP TABLE IF EXISTS "questiontags" CASCADE;
DROP TABLE IF EXISTS  "answercomments" CASCADE;
DROP TABLE IF EXISTS  "questioncomments" CASCADE;

