DROP TABLE IF EXISTS "Warning" CASCADE;

DROP TABLE IF EXISTS "Badge" CASCADE;

DROP TABLE IF EXISTS "Ban" CASCADE;

DROP TABLE IF EXISTS "Category" CASCADE;

DROP TABLE IF EXISTS "Comment" CASCADE;

DROP TABLE IF EXISTS "Question" CASCADE;

DROP TABLE IF EXISTS "UserBadge" CASCADE;

DROP TABLE IF EXISTS "Location" CASCADE;

DROP TABLE IF EXISTS "Question" CASCADE;

DROP TABLE IF EXISTS "Publication" CASCADE;

DROP TABLE IF EXISTS "ModRegister" CASCADE;

DROP TABLE IF EXISTS "Answer" CASCADE;

DROP TABLE IF EXISTS "Tag" CASCADE;

DROP TABLE IF EXISTS "UserRole" CASCADE;

DROP TABLE IF EXISTS "User" CASCADE;

DROP TABLE IF EXISTS "Vote" CASCADE;

DROP TABLE IF EXISTS "QuestionTag" CASCADE;

DROP TABLE IF EXISTS  "CommentAnswer" CASCADE;
DROP TABLE IF EXISTS  "CommentQuestion" CASCADE;